### ISSUE TITLE
[Front End] Input form

### ISSUE THREAD

**Issue by sarahaguasvivas** [correlllab/nn4mc_web#2]
- Initial dropdown box where you can select from hdf5 or PyTorch
- - if hdf5:
            - 1 input box will show up to take in an `.hdf5` or `.h5`
- - if PyTorch
           - 2 input boxes where you can upload `.pk` and a `.py`

- Submit button to upload and submit files

**Comment by TwirlingTechGoddess** [comment]
I get this error when trying to run the program
<img width="421" alt="Screen Shot 2020-05-19 at 2 39 43 PM" src="https://user-images.githubusercontent.com/17820472/82376018-b6fc5100-99de-11ea-8e7b-58f1a1c2b538.png">

**Comment by sarahaguasvivas** [comment]
Seems like this error was solved: I believe these were the steps to resolve it:

- pip install nn4mc
- Resolve issue with nn4mc_py and the Python requirements. 

I believe LeeLee had Python2.7 and the software requires Python3.5+ @RS-Coop, correct this if it is wrong.

**Comment by RS-Coop** [comment]
For the specific error referred above the solution is `pip install nn4mc`

It should be noted that nn4mc_py is a Python3 application and thus the required steps should be taken to ensure that this does not cause problems. This may include using `pip3 install nn4mc`, or installing in a virtual environment. 

nn4mc_py will be updated to make it more clear that Python3 is required.
